## A simple example of Naive Bayes

In [1]:
#Import Library of Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
import numpy as np

#assigning predictor and target variables
X= np.array([[-3,7],[1,5], [1,2], [-2,0], [2,3], [-4,0], [-1,1], [1,1], [-2,2], [2,7], [-4,1], [-2,7]])
y = np.array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])
#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets 
model.fit(X, y)

#Predict Output 
predicted= model.predict([[1,2],[3,4]])
print(predicted)


[3 4]


## Over Iris Datase - Naive Bayes

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(iris.data, iris.target).predict(iris.data)
print("Number of mislabeled points out of a total %d points : %d" % (iris.data.shape[0],(iris.target != y_pred).sum()))

Number of mislabeled points out of a total 150 points : 6


In [3]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, iris.target)

0.95999999999999996

## Iris dataset using random shuffling and split

In [14]:
import numpy as np
seq = np.random.permutation(150)
X = iris.data[seq]
y = iris.target[seq]
X_train, X_test, y_train, y_test = X[:100], X[100:], y[:100], y[100:]
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.95999999999999996

## Another Example with Categorical Data

In [24]:
X = np.array([["Sunny"],["Overcast"], ["Overcast"], ["Rainy"], ["Sunny"]])
y = np.array([1, 0, 1, 0, 0])

from sklearn.preprocessing import LabelBinarizer
enc = LabelBinarizer()
# encoder = OneHotEncoder()
# housing_cat_1hot = encoder.fit_transform(housing_cat_encoded.reshape(-1,1))

X1 = enc.fit_transform(X.reshape(-1,1))
gnb = GaussianNB()
gnb.fit(X1, y)

X1

array([[0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
# Rainy
gnb.predict([[0, 1, 0]])

array([0])

In [30]:
# Sunny
gnb.predict([[0, 0, 1]])

array([1])

In [31]:
# Overcast
gnb.predict([[1, 0, 0]])

array([1])

In [32]:
enc.classes_

array(['Overcast', 'Rainy', 'Sunny'],
      dtype='<U8')

In [33]:
gnb.predict_proba([[1, 0, 0]])

array([[  3.36351842e-05,   9.99966365e-01]])