In [4]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [8]:
b = np.array((3, 4, 5))

In [9]:
type(b)

numpy.ndarray

In [16]:
x = np.zeros((2,3,4))  
print(x)


[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [11]:
x = np.zeros((3,4))  
print(x)
type(x.dtype)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


numpy.dtype

In [12]:
x.shape

(3, 4)

In [17]:
y = np.ones( (3,4), dtype=np.float64 )  
y

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
print(x.dtype)
print(y.dtype)

float64
float64


In [19]:
np.full( (3,4), 0.11 )

array([[ 0.11,  0.11,  0.11,  0.11],
       [ 0.11,  0.11,  0.11,  0.11],
       [ 0.11,  0.11,  0.11,  0.11]])

In [22]:
np.full( (3,4), np.pi )

array([[ 3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265]])

In [26]:
np.arange( 10, 30, 2 )

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
%timeit x

22.4 ns ± 0.0106 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [29]:
np.arange( 0, 2, 0.5 ) 

array([ 0. ,  0.5,  1. ,  1.5])

In [30]:
x = [
        [
            [1],
            [1], 
            [1],
            [1]
        ],
        [
            [1],
            [1], 
            [1],
            [1]
        ]
]

In [33]:
xx = np.array(x)
print(xx.shape)
print(xx)

(2, 4, 1)
[[[1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]]]


In [38]:
np.linspace(1, 10, 25)

array([  1.   ,   1.375,   1.75 ,   2.125,   2.5  ,   2.875,   3.25 ,
         3.625,   4.   ,   4.375,   4.75 ,   5.125,   5.5  ,   5.875,
         6.25 ,   6.625,   7.   ,   7.375,   7.75 ,   8.125,   8.5  ,
         8.875,   9.25 ,   9.625,  10.   ])

In [40]:
np.linspace(0, 5/3, 6)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
        1.66666667])

In [39]:
# Make a 2x3 matrix having random floats between 0 and 1:
np.random.rand(2,3)

array([[ 0.89939305,  0.70750446,  0.40601184],
       [ 0.28488237,  0.85547077,  0.70560823]])

In [40]:
x = np.empty((2,3))

In [53]:
x

array([[ 0.21288689,  0.20662218,  0.78018623],
       [ 0.35294004,  0.07347101,  0.54552084]])

In [54]:
x.ndim

2

In [55]:
x.shape

(2, 3)

In [59]:
x.size


6

In [58]:
x[0]

array([ 0.21288689,  0.20662218,  0.78018623])

In [41]:
c = np.arange(1, 5)

In [42]:
c

array([1, 2, 3, 4])

In [43]:
c.dtype

dtype('int64')

In [44]:
c.itemsize

8

In [45]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [46]:
b = a.reshape(2, 3)
print(b)

[[0 1 2]
 [3 4 5]]


In [47]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [51]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[1]

5

In [52]:
a[2:5]

array([ 3, 19, 13])

In [55]:
print(a[2::2])
print(a[2::3])
print(a[::-1])

[ 3 13  3]
[3 7]
[ 3  7 13 19  3  5  1]


In [61]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
print(a)
a[1:3] = -1
print(a)

[ 1  5  3 19 13  7  3]
[ 1 -1 -1 19 13  7  3]


In [71]:
b = [1, 2, 5, 7, 8]

In [72]:
b[1:3] = -1


TypeError: can only assign an iterable

In [62]:
a = np.array([1, 2, 5, 7, 8])
a_slice = a[1:5] # 2, 5, 7, 8
a_slice[1] = 1000
print(a)

[   1    2 1000    7    8]


In [63]:
another_slice = a[2:6].copy()
another_slice[1] = 23333  
print(another_slice) #Updated
print(a) #Unchanged

[ 1000 23333     8]
[   1    2 1000    7    8]


In [74]:
x = np.random.rand(4,5)

In [75]:
x

array([[ 0.55994735,  0.32962552,  0.85814361,  0.19258212,  0.50078572],
       [ 0.48840192,  0.63915096,  0.2028576 ,  0.48626312,  0.04789044],
       [ 0.90868324,  0.56080676,  0.15256665,  0.90885087,  0.10891534],
       [ 0.12090472,  0.67938645,  0.68972781,  0.53446143,  0.16947415]])

In [66]:
x[1]

array([ 0.31854447,  0.45221485,  0.21210511,  0.69835135,  0.59217018,
        0.38524412,  0.70401389,  0.89614996])

In [68]:
print(x[1][1])
print(x[1, 1])

0.452214850973
0.452214850973


In [76]:
x[0:2, 0:2]

array([[ 0.55994735,  0.32962552],
       [ 0.48840192,  0.63915096]])

In [77]:
x = np.random.rand(5,5, 5)

In [78]:
x

array([[[ 0.59648891,  0.10162489,  0.57657282,  0.62543456,  0.5671127 ],
        [ 0.46245426,  0.73242947,  0.43806255,  0.19851733,  0.37004634],
        [ 0.98222474,  0.43583652,  0.42384156,  0.57893023,  0.42334059],
        [ 0.73013833,  0.63074741,  0.62226984,  0.62894135,  0.93535332],
        [ 0.28735721,  0.94946183,  0.71656386,  0.8562498 ,  0.22565064]],

       [[ 0.50370903,  0.03523531,  0.18102288,  0.34077528,  0.31003367],
        [ 0.24424363,  0.95300311,  0.37349415,  0.96949979,  0.58389772],
        [ 0.36419596,  0.52330188,  0.87537242,  0.56963827,  0.43947746],
        [ 0.71755677,  0.73146329,  0.21731029,  0.4456562 ,  0.48412024],
        [ 0.14774364,  0.83340309,  0.58982263,  0.92250118,  0.96296739]],

       [[ 0.48033917,  0.61723935,  0.46213739,  0.91353783,  0.14385419],
        [ 0.51389764,  0.88270377,  0.43674932,  0.36818862,  0.53844015],
        [ 0.03940884,  0.87161287,  0.50471399,  0.13127129,  0.18404074],
        [ 0.02691279,

In [80]:
x[0:2, 0:2, 0:3]

array([[[ 0.59648891,  0.10162489,  0.57657282],
        [ 0.46245426,  0.73242947,  0.43806255]],

       [[ 0.50370903,  0.03523531,  0.18102288],
        [ 0.24424363,  0.95300311,  0.37349415]]])

In [81]:
a = np.arange(12).reshape(3, 4)

In [82]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
rows_on = np.array([ True, False, True])

In [84]:
rows_on

array([ True, False,  True], dtype=bool)

In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a[rows_on]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [94]:
a = np.array( [20, 30, 40, 50] )
b = np.arange( 4 )
print(a)
print(b)
c = a + b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]


In [95]:
c = a - b
c

array([20, 29, 38, 47])

In [96]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )
print(A*B)                         # element wise product

print([[1*2, 1*0],
       [0*3, 1*4]])

[[2 0]
 [0 4]]
[[2, 0], [0, 4]]


In [97]:
print(np.dot(A, B))
print([[1*2+ 1*3, 1*0+ 1*4],
       [0*2+1*3, 0*0+1*4]])

[[5 4]
 [3 4]]
[[5, 4], [3, 4]]


In [130]:
# np.arange - Creating sequence of Numbers

a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a / b
print(c)

[ 20.          15.          13.33333333  12.5       ]


In [129]:
c

array([ 20.        ,  15.        ,  13.33333333,  12.5       ])

In [131]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a // b
c


array([20, 15, 13, 12])

In [133]:
#Modulus operator can be applied on NumPy arrays as shown below. They apply element wise.
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a % b
c


array([0, 0, 1, 2])

In [134]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a ** b
c



array([     20,     900,   64000, 6250000])

In [135]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False], dtype=bool)

In [136]:
m < 25 

array([ True,  True, False, False], dtype=bool)

In [137]:
m[m < 25]

array([20, -5])

In [152]:
h = np.arange(5).reshape(1, 1, 5)
print(h)
print(h.shape)

[[[0 1 2 3 4]]]
(1, 1, 5)


In [146]:
b = np.array([10, 20, 30, 40, 50])
b.reshape(1,1,5)

array([[[10, 20, 30, 40, 50]]])

In [153]:
x = h + [10, 20, 30, 40, 50]
print(x)
print(x.shape)

[[[10 21 32 43 54]]]
(1, 1, 5)


In [144]:
h + [[[10, 20, 30, 40, 50]]]

array([[[10, 21, 32, 43, 54]]])

In [147]:
h + b.reshape(1,1,5)

array([[[10, 21, 32, 43, 54]]])

In [148]:
k = np.arange(6).reshape(2, 3)

In [149]:
k


array([[0, 1, 2],
       [3, 4, 5]])

In [151]:
k + [100, 200, 300] 

array([[100, 201, 302],
       [103, 204, 305]])

In [155]:
 k + [33, 44]

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [157]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print("mean =", a.mean())

mean = 6.76666666667


In [158]:
np.prod(a)

-71610.0

In [159]:
print(-2.5* 3.1* 7*10*11*12)

-71610.0


In [181]:
import math
a = np.array([1,3,4])
m = np.mean(a)
print(m)
print(a -m)
x = (a-m)**2
print(x)
s = np.sum(x)
print(s)
v = np.var(a)
print(v)
print(v*len(a))
print(np.std(a))
print(math.sqrt(s/len(a)))

2.66666666667
[-1.66666667  0.33333333  1.33333333]
[ 2.77777778  0.11111111  1.77777778]
4.66666666667
1.55555555556
4.66666666667
1.24721912892
1.247219128924647


In [182]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [183]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [3]:
import numpy as np
a = np.array([[10,20],[30,40]])
b = np.array([1])
print(a+b)

[[11 21]
 [31 41]]


In [4]:
import numpy as np
import pandas as pd

In [1]:
weights = {"alice": 68, "bob": 83, "colin": 86, "darwin": 68}

In [2]:
weights

{'alice': 68, 'bob': 83, 'colin': 86, 'darwin': 68}

In [5]:
s3 = pd.Series(weights)

In [7]:
s3 + s3

alice     136
bob       166
colin     172
darwin    136
dtype: int64

In [8]:
people["birthyear"]

NameError: name 'people' is not defined

In [9]:
people = pd.DataFrame(people_dict)

NameError: name 'people_dict' is not defined

In [10]:
d2 = pd.DataFrame(
        people_dict,
        columns=["birthyear", "weight", "height"],
        index=["bob", "alice", "eugene"]
     )

NameError: name 'people_dict' is not defined