In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [9]:
a.ndim

1

In [8]:
type(a)

numpy.ndarray

In [13]:
b = np.array((3, 4, 5))
b

array([3, 4, 5])

In [11]:
type(b)

numpy.ndarray

In [11]:
x = np.zeros((2,3,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [14]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
x = np.zeros((3,4))  
print(x)
type(x.dtype)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.dtype

In [14]:
x.shape

(3, 4)

In [3]:
y = np.ones( (3,4), dtype=np.float64 )  
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
print(x.dtype)
print(y.dtype)

In [9]:
np.full( (3,4), 0.11)

array([[ 0.11,  0.11,  0.11,  0.11],
       [ 0.11,  0.11,  0.11,  0.11],
       [ 0.11,  0.11,  0.11,  0.11]])

In [15]:
np.full( (3,4), np.pi )

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [16]:
np.arange( 10, 30, 2 )

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [5]:
x

NameError: name 'x' is not defined

In [17]:
%timeit np.arange(1, 100, 0.1)

1.8 µs ± 0.486 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [29]:
np.arange( 0, 2, 0.5 )

array([ 0. ,  0.5,  1. ,  1.5])

In [9]:
np.arange( 0, 20, 0.005 ).shape

(4000,)

In [18]:
x = [
        [
            1,2,3,4
        ],
        [
            1,2,2,2
        ]
]
x1 = np.array(x)
print(x1.shape)

(2, 4)


In [19]:
three_d_array = np.full((2,3,4), 0.11)

In [22]:
three_d_array.size

24

In [27]:
three_d_array.reshape(-1, 6)

array([[0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11]])

In [28]:
three_d_array.shape

(2, 3, 4)

In [12]:
x = [
        [
            [1, 3],
            [1, 3], 
            [1, 3],
            [1, 3]
        ],
#         [
#             [1, 3],
#             [1, 3], 
#             [1, 3],
#             [1, 3]
#         ]
]

In [13]:
xx = np.array(x)
print(xx.shape)
print(xx)

(1, 4, 2)
[[[1 3]
  [1 3]
  [1 3]
  [1 3]]]


In [16]:
np.linspace(0, 10, 3)

array([  0.,   5.,  10.])

In [25]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [40]:
np.linspace(0, 5/3, 6)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
        1.66666667])

How many dimension are there in a dataset having list of pictures?
    * First: # of pics
    * Second: x axis
    * Third: y axis
    * Forth: r, g, b

In [10]:
# Make a 2x3 matrix having random floats between 0 and 1:
x = np.random.rand(2,3)

In [5]:
x = np.empty((2,3))

In [6]:
x

array([[1.03063392e-113, 1.05894612e-153, 1.03106417e-259],
       [2.92552507e-014, 5.04524735e+223, 6.99416066e-009]])

In [25]:
x.ndim

2

In [55]:
x.shape

(2, 3)

In [31]:
x.size


6

In [11]:
x

array([[0.98091489, 0.19111819, 0.12349174],
       [0.2272532 , 0.58024774, 0.98112842]])

In [12]:
x[0]

array([0.98091489, 0.19111819, 0.12349174])

In [13]:
x[1]

array([0.2272532 , 0.58024774, 0.98112842])

In [14]:
x[1][0]

0.2272532000406674

In [15]:
x[1,0]

0.2272532000406674

In [16]:
c = np.arange(1, 5)

In [17]:
c

array([1, 2, 3, 4])

In [43]:
c.dtype

dtype('int64')

In [36]:
c.itemsize

NameError: name 'c' is not defined

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [30]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [18]:
a = np.arange(24)
print(a)
b = a.reshape(2,3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
b.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
# Create a 2x4 array filled with numbers between 0 to 2
a = np.random.rand(2,4)*10

In [27]:
a

array([[4.21068213, 8.35014573, 3.00980581, 4.7235906 ],
       [5.46269326, 4.63231872, 6.71666015, 6.34382649]])

In [50]:
a = np.arange(50)
print(a)
print(a.reshape(-1, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [28]:
np.RAISE?

In [47]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [37]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[1]

5

In [52]:
a[2:5]

array([ 3, 19, 13])

In [35]:
a

array([0, 1, 2, 3, 4, 5])

In [38]:
a[1:6:2]

array([1, 3, 5])

In [30]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import numpy as np',
  'x = np.empty((2,3))',
  'x = np.empty((2,3))',
  'x',
  'x = np.empty((2,3))',
  'x',
  '# Make a 2x3 matrix having random floats between 0 and 1:\nnp.random.rand(2,3)',
  'x',
  'x',
  '# Make a 2x3 matrix having random floats between 0 and 1:\nx = np.random.rand(2,3)',
  'x',
  'x[0]',
  'x[1]',
  'x[1][0]',
  'x[1,0]',
  'c = np.arange(1, 5)',
  'c',
  'a = np.arange(24)\nprint(a)\nb = a.reshape(2,3,4)\nprint(b)',
  'b.reshape(-1)',
  "# Create a 2x4 array filled with numbers between 0 to 2\nget_ipython().set_next_input('a = np.random.rand');get_ipython().run_line_magic('pinfo', 'np.random.rand')",
  '# Create a 2x4 array filled with numbers between 0 to 2\na = np.random.rand(2,3)',
 

In [55]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

so how to get al values greater than 1 and less than 10?
1 <= x < 10

In [34]:
x = np.random.rand(6,6)

In [35]:
x*9 + 1

array([[2.66304378, 1.74317461, 8.58342831, 7.60998047, 6.49294371,
        9.95589081],
       [5.24076309, 5.33226314, 7.5813461 , 2.12616739, 3.85366332,
        8.93562503],
       [9.33420367, 2.90315844, 2.73373385, 9.96533083, 6.17955347,
        9.44672596],
       [4.26619649, 7.93767994, 9.92160565, 1.06867886, 2.00250024,
        5.79331075],
       [4.34036127, 6.79161342, 9.0644083 , 6.63379181, 1.35739678,
        5.32412788],
       [4.73441339, 4.78760857, 8.93890289, 6.65713699, 5.2361747 ,
        8.42075388]])

In [36]:
a

array([[4.21068213, 8.35014573, 3.00980581, 4.7235906 ],
       [5.46269326, 4.63231872, 6.71666015, 6.34382649]])

In [43]:
a = np.arange(24)

In [44]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
a[17]

17

In [48]:
a[5:7]

array([5, 6])

In [55]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23])

In [54]:
a[:3]

array([0, 1, 2])

In [56]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
a[:10:2]

array([0, 2, 4, 6, 8])

In [61]:
a[:10:-1]

array([23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [62]:
print(a[2::2])

[ 2  4  6  8 10 12 14 16 18 20 22]


In [63]:
print(a[2::3])

[ 2  5  8 11 14 17 20 23]


In [64]:
print(a[::-1])

[23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [65]:
print(a[::-3])

[23 20 17 14 11  8  5  2]


In [44]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
print(a)
a[1:3] = -1
print(a)

[ 1  5  3 19 13  7  3]
[ 1 -1 -1 19 13  7  3]


In [45]:
b = [1, 2, 5, 7, 8]

In [46]:
b[1:3] = -1


TypeError: can only assign an iterable

In [66]:
a = np.array([1, 2, 5, 7, 8])
a

array([1, 2, 5, 7, 8])

In [68]:
a_slice = a[1:5] # 2, 5, 7, 8
a_slice

array([2, 5, 7, 8])

In [70]:
a_slice[1] = 1000
a_slice

array([   2, 1000,    7,    8])

In [71]:
a

array([   1,    2, 1000,    7,    8])

In [72]:
a_slice_copy = a_slice.copy()
a_slice_copy[3] = 800
a_slice_copy

array([   2, 1000,    7,  800])

In [73]:
print(a)
print(a_slice)

[   1    2 1000    7    8]
[   2 1000    7    8]


In [63]:
another_slice = a[2:6].copy()
another_slice[1] = 23333  
print(another_slice) #Updated
print(a) #Unchanged

[ 1000 23333     8]
[   1    2 1000    7    8]


In [89]:
x = np.array([1,2])
y = np.array([[2, 3], [4,5]])

In [90]:
y[0] = x

In [91]:
y[1] = x

In [92]:
y

array([[1, 2],
       [1, 2]])

In [94]:
x[0] = 100

In [95]:
y

array([[1, 2],
       [1, 2]])

In [61]:
a + a/2.9

array([   1.34482759,    2.68965517, 1344.82758621,    9.4137931 ,
         10.75862069])

In [100]:
x = np.random.rand(4,5)

In [101]:
x

array([[0.44997646, 0.09582722, 0.64409086, 0.34030565, 0.05960966],
       [0.90352111, 0.34461246, 0.35671107, 0.18549954, 0.64370516],
       [0.78627125, 0.01049569, 0.40552024, 0.64833772, 0.70732595],
       [0.48893513, 0.86617274, 0.67568517, 0.45285252, 0.70655446]])

In [102]:
x[1]

array([0.90352111, 0.34461246, 0.35671107, 0.18549954, 0.64370516])

In [103]:
print(x[1][1])
print(x[1, 1])

0.3446124586903633
0.3446124586903633


In [104]:
x[0:2, 0:2]

array([[0.44997646, 0.09582722],
       [0.90352111, 0.34461246]])

In [14]:
x = np.random.rand(3, 3, 3)

In [15]:
x

array([[[0.18410005, 0.0651805 , 0.21989363],
        [0.55577454, 0.09870701, 0.52727274],
        [0.82792827, 0.48752357, 0.40812787]],

       [[0.65847682, 0.81790039, 0.98569846],
        [0.38276324, 0.9022624 , 0.05164668],
        [0.78644582, 0.11431479, 0.20598313]],

       [[0.87385351, 0.03668779, 0.48537833],
        [0.34792399, 0.59105191, 0.30141866],
        [0.56178169, 0.26866191, 0.68301216]]])

In [17]:
x[0:2, 0:2, 1:3]

array([[[0.0651805 , 0.21989363],
        [0.09870701, 0.52727274]],

       [[0.81790039, 0.98569846],
        [0.9022624 , 0.05164668]]])

In [10]:
x[1:4:2, 0:2, 0:3]

array([[[0.87635273, 0.12237062, 0.83052763],
        [0.30310025, 0.52611421, 0.39942328]],

       [[0.22695107, 0.05080312, 0.72781762],
        [0.52294718, 0.76220147, 0.35185516]]])

In [22]:
a = np.arange(12).reshape(3, -1)

In [23]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
rows_on = np.array([ True, False, True])

In [25]:
rows_on

array([ True, False,  True])

In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a[rows_on]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a[[True, False, True]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [31]:
a[:,[True, False, True, False]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [38]:
x = np.random.rand(5,3)
print(x)

[[0.71517002 0.17689028 0.55069486]
 [0.80178347 0.92556653 0.30575007]
 [0.13120788 0.98396418 0.14923023]
 [0.26936805 0.28098552 0.42003877]
 [0.68312858 0.2179261  0.06972168]]


In [41]:
x[-1, 1]

0.2179261033474179

In [39]:
x[:,2]

array([0.55069486, 0.30575007, 0.14923023, 0.42003877, 0.06972168])

In [49]:
x[2:4, 1]

array([0.98396418, 0.28098552])

In [50]:
x

array([[0.71517002, 0.17689028, 0.55069486],
       [0.80178347, 0.92556653, 0.30575007],
       [0.13120788, 0.98396418, 0.14923023],
       [0.26936805, 0.28098552, 0.42003877],
       [0.68312858, 0.2179261 , 0.06972168]])

Create a 2d array such that it has 5 rows and only 1 column having values of last column

In [60]:
y = x[:,2].reshape(-1, 1)

In [61]:
y.shape

(5, 1)

In [45]:
p = np.arange(10)
print(p)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
p[2:8:3]

array([2, 5])

In [42]:
x[2:3:1, :]

array([[0.13120788, 0.98396418, 0.14923023]])

In [ ]:
x[a:b:c, d:e:f]
a -> start, 0
b -> end, length
c --> skip, 1
: --> 0:length, 1

In [69]:
a = np.array([[2,4]])
print(a.shape)
b = np.array([1,5])
print(b.shape)
c = a+b
print(c.shape)

(1, 2)
(2,)
(1, 2)
(2,)


In [62]:
a = np.array( [20, 30, 40, 50] )
b = np.arange( 4 )
print(a)
print(b)
c = a + b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]


In [66]:
d= []
for i in range(a.size):
    d.append(a[i] + b[i])
print(d)

[20, 31, 42, 53]


In [67]:
np.array([1,4]) + np.array([1,2,4,5])

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [68]:
c = a - b
c

array([20, 29, 38, 47])

In [69]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )
print(A*B)                         # element wise product

print([[1*2, 1*0],
       [0*3, 1*4]])

[[2 0]
 [0 4]]
[[2, 0], [0, 4]]


In [71]:
print(np.dot(A, B))
print([[1*2+ 1*3, 1*0+ 1*4],
       [0*2+1*3, 0*0+1*4]])

[[5 4]
 [3 4]]
[[5, 4], [3, 4]]


In [72]:
# np.arange - Creating sequence of Numbers

a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a / b
print(c)

[20.         15.         13.33333333 12.5       ]


In [74]:
np.power(a, b)

array([     20,     900,   64000, 6250000])

In [129]:
c

array([ 20.        ,  15.        ,  13.33333333,  12.5       ])

In [131]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a // b
c


array([20, 15, 13, 12])

In [133]:
#Modulus operator can be applied on NumPy arrays as shown below. They apply element wise.
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a % b
c

array([0, 0, 1, 2])

In [134]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a ** b
c



array([     20,     900,   64000, 6250000])

In [135]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False], dtype=bool)

In [136]:
m < 25 

array([ True,  True, False, False], dtype=bool)

In [137]:
m[m < 25]

array([20, -5])

In [152]:
h = np.arange(5).reshape(1, 1, 5)
print(h)
print(h.shape)

[[[0 1 2 3 4]]]
(1, 1, 5)


In [146]:
b = np.array([10, 20, 30, 40, 50])
b.reshape(1,1,5)

array([[[10, 20, 30, 40, 50]]])

In [153]:
x = h + [10, 20, 30, 40, 50]
print(x)
print(x.shape)

[[[10 21 32 43 54]]]
(1, 1, 5)


In [144]:
h + [[[10, 20, 30, 40, 50]]]

array([[[10, 21, 32, 43, 54]]])

In [147]:
h + b.reshape(1,1,5)

array([[[10, 21, 32, 43, 54]]])

In [148]:
k = np.arange(6).reshape(2, 3)

In [149]:
k


array([[0, 1, 2],
       [3, 4, 5]])

In [151]:
k + [100, 200, 300] 

array([[100, 201, 302],
       [103, 204, 305]])

In [155]:
 k + [33, 44]

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [157]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print("mean =", a.mean())

mean = 6.76666666667


In [158]:
np.prod(a)

-71610.0

In [159]:
print(-2.5* 3.1* 7*10*11*12)

-71610.0


In [181]:
import math
a = np.array([1,3,4])
m = np.mean(a)
print(m)
print(a -m)
x = (a-m)**2
print(x)
s = np.sum(x)
print(s)
v = np.var(a)
print(v)
print(v*len(a))
print(np.std(a))
print(math.sqrt(s/len(a)))

2.66666666667
[-1.66666667  0.33333333  1.33333333]
[ 2.77777778  0.11111111  1.77777778]
4.66666666667
1.55555555556
4.66666666667
1.24721912892
1.247219128924647


In [182]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [183]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [3]:
import numpy as np
a = np.array([[10,20],[30,40]])
b = np.array([1])
print(a+b)

[[11 21]
 [31 41]]


In [4]:
import numpy as np
import pandas as pd

In [1]:
weights = {"alice": 68, "bob": 83, "colin": 86, "darwin": 68}

In [2]:
weights

{'alice': 68, 'bob': 83, 'colin': 86, 'darwin': 68}

In [5]:
s3 = pd.Series(weights)

In [7]:
s3 + s3

alice     136
bob       166
colin     172
darwin    136
dtype: int64

In [8]:
people["birthyear"]

NameError: name 'people' is not defined

In [9]:
people = pd.DataFrame(people_dict)

NameError: name 'people_dict' is not defined

In [10]:
d2 = pd.DataFrame(
        people_dict,
        columns=["birthyear", "weight", "height"],
        index=["bob", "alice", "eugene"]
     )

NameError: name 'people_dict' is not defined

In [81]:
a = np.array([[1, 2, 3],
[4, 5, 6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [80]:
a.sum(axis=0)

array([5, 7, 9])

In [79]:
a.sum(axis=1)

array([ 6, 15])

In [82]:
b = np.array([[.1, .2, .3],
[.4, .5, .6]])

In [84]:
from numpy import linalg

In [90]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)

In [89]:
solution

array([-3.,  2.])

In [91]:
coeffs.dot(solution)

array([ 6., -9.])