In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
b = np.array((3, 4, 5))

In [9]:
type(b)

numpy.ndarray

In [5]:
x = np.zeros((2,3,4))  
print(x)


[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [6]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [7]:
x = np.zeros((3,4))  
print(x)
type(x.dtype)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


numpy.dtype

In [8]:
x.shape

(3, 4)

In [17]:
y = np.ones( (3,4), dtype=np.float64 )  
y

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
print(x.dtype)
print(y.dtype)

float64
float64


In [9]:
np.full( (3,4), 0.11 )

array([[ 0.11,  0.11,  0.11,  0.11],
       [ 0.11,  0.11,  0.11,  0.11],
       [ 0.11,  0.11,  0.11,  0.11]])

In [10]:
np.full( (3,4), np.pi )

array([[ 3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265]])

In [26]:
np.arange( 10, 30, 2 )

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [11]:
x

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [21]:
%timeit x

22.4 ns ± 0.0106 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [29]:
np.arange( 0, 2, 0.5 ) 

array([ 0. ,  0.5,  1. ,  1.5])

In [14]:
x = [
        [
            1,2,3,4
        ],
        [
            1,2,2,2
        ]
]
x1 = np.array(x)
print(x1.shape)

(2, 4)


In [12]:
x = [
        [
            [1, 3],
            [1, 3], 
            [1, 3],
            [1, 3]
        ],
        [
            [1, 3],
            [1, 3], 
            [1, 3],
            [1, 3]
        ]
]

In [13]:
xx = np.array(x)
print(xx.shape)
print(xx)

(2, 4, 2)
[[[1 3]
  [1 3]
  [1 3]
  [1 3]]

 [[1 3]
  [1 3]
  [1 3]
  [1 3]]]


In [16]:
np.linspace(0, 10, 3)

array([  0.,   5.,  10.])

In [40]:
np.linspace(0, 5/3, 6)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
        1.66666667])

In [19]:
# Make a 2x3 matrix having random floats between 0 and 1:
np.random.rand(2,3)

array([[ 0.11986549,  0.59448042,  0.55987719],
       [ 0.11868417,  0.07005783,  0.41551619]])

In [23]:
x = np.empty((2,3))

In [24]:
x

array([[ 0.11986549,  0.59448042,  0.55987719],
       [ 0.11868417,  0.07005783,  0.41551619]])

In [25]:
x.ndim

2

In [55]:
x.shape

(2, 3)

In [59]:
x.size


6

In [58]:
x[0]

array([ 0.21288689,  0.20662218,  0.78018623])

In [41]:
c = np.arange(1, 5)

In [42]:
c

array([1, 2, 3, 4])

In [43]:
c.dtype

dtype('int64')

In [44]:
c.itemsize

8

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [30]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [47]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [51]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[1]

5

In [52]:
a[2:5]

array([ 3, 19, 13])

In [35]:
a

array([0, 1, 2, 3, 4, 5])

In [38]:
a[1:6:2]

array([1, 3, 5])

In [43]:
locals()

{'In': ['',
  'import numpy as np',
  'a = np.array([1, 2, 3])\na',
  'type(a)',
  'b = np.array((3, 4, 5))',
  'x = np.zeros((2,3,4))  \nprint(x)',
  'np.zeros(3)',
  'x = np.zeros((3,4))  \nprint(x)\ntype(x.dtype)',
  'x.shape',
  'np.full( (3,4), 0.11 )',
  'np.full( (3,4), np.pi )',
  'x',
  'x = [\n        [\n            [1, 3],\n            [1, 3], \n            [1, 3],\n            [1, 3]\n        ],\n        [\n            [1, 3],\n            [1, 3], \n            [1, 3],\n            [1, 3]\n        ]\n]',
  'xx = np.array(x)\nprint(xx.shape)\nprint(xx)',
  'x = [\n        [\n            1,2,3,4\n        ],\n        [\n            1,2,2,2\n        ]\n]\nx1 = np.array(x)\nprint(x1.shape)',
  'np.linspace(1, 10, 3)',
  'np.linspace(0, 10, 3)',
  '# Make a 2x3 matrix having random floats between 0 and 1:\nnp.random.rand(2,3)',
  '# Make a 2x3 matrix having random floats between 0 and 1:\nnp.random.rand(2,3,5)',
  '# Make a 2x3 matrix having random floats between 0 and 1:\nnp.ran

In [55]:
print(a[2::2])
print(a[2::3])
print(a[::-1])

[ 3 13  3]
[3 7]
[ 3  7 13 19  3  5  1]


In [44]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
print(a)
a[1:3] = -1
print(a)

[ 1  5  3 19 13  7  3]
[ 1 -1 -1 19 13  7  3]


In [45]:
b = [1, 2, 5, 7, 8]

In [46]:
b[1:3] = -1


TypeError: can only assign an iterable

In [62]:
a = np.array([1, 2, 5, 7, 8])
a_slice = a[1:5] # 2, 5, 7, 8
a_slice[1] = 1000
print(a)

[   1    2 1000    7    8]


In [63]:
another_slice = a[2:6].copy()
another_slice[1] = 23333  
print(another_slice) #Updated
print(a) #Unchanged

[ 1000 23333     8]
[   1    2 1000    7    8]


In [48]:
x = np.random.rand(4,5)

In [49]:
x

array([[ 0.51413037,  0.69482588,  0.2815293 ,  0.6633343 ,  0.14940355],
       [ 0.00840067,  0.89072513,  0.7041798 ,  0.24091724,  0.20693832],
       [ 0.9248849 ,  0.41156005,  0.37849707,  0.43912137,  0.62486803],
       [ 0.63539357,  0.877726  ,  0.00489644,  0.68040519,  0.45526226]])

In [50]:
x[1]

array([ 0.00840067,  0.89072513,  0.7041798 ,  0.24091724,  0.20693832])

In [51]:
print(x[1][1])
print(x[1, 1])

0.890725130479
0.890725130479


In [52]:
x[0:2, 0:2]

array([[ 0.51413037,  0.69482588],
       [ 0.00840067,  0.89072513]])

In [54]:
x = np.random.rand(5,5, 5)

In [55]:
x

array([[[ 0.51226495,  0.26909906,  0.04443641,  0.17885857,  0.70970813],
        [ 0.91939958,  0.82692282,  0.55314942,  0.17791506,  0.12887349],
        [ 0.90321746,  0.02843024,  0.03446226,  0.23392365,  0.69160437],
        [ 0.40023325,  0.34690498,  0.11826865,  0.38343352,  0.75649193],
        [ 0.85830314,  0.1175052 ,  0.82304463,  0.34899505,  0.44988304]],

       [[ 0.52975774,  0.90227423,  0.11679158,  0.06498131,  0.02227412],
        [ 0.40456117,  0.251357  ,  0.49946791,  0.86838691,  0.45138521],
        [ 0.45319829,  0.0869838 ,  0.16558579,  0.69451768,  0.63049735],
        [ 0.60070485,  0.83917778,  0.06653621,  0.83058707,  0.36060204],
        [ 0.22933404,  0.9420062 ,  0.98944617,  0.05125053,  0.75802805]],

       [[ 0.25358781,  0.34719762,  0.97000838,  0.92665438,  0.42873555],
        [ 0.04626455,  0.02184896,  0.69235594,  0.79649929,  0.81373545],
        [ 0.32861344,  0.31435248,  0.72954942,  0.44632331,  0.37561862],
        [ 0.63358158,

In [53]:
x[0:2, 0:2, 0:3]

IndexError: too many indices for array

In [56]:
a = np.arange(12).reshape(3, 4)

In [57]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
rows_on = np.array([ True, False, True])

In [59]:
rows_on

array([ True, False,  True], dtype=bool)

In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a[rows_on]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [69]:
a = np.array([[2,4]])
print(a.shape)
b = np.array([1,5])
print(b.shape)
c = a+b
print(c.shape)

(1, 2)
(2,)
(1, 2)
(2,)


In [94]:
a = np.array( [20, 30, 40, 50] )
b = np.arange( 4 )
print(a)
print(b)
c = a + b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]


In [73]:
np.array([1,4]) + np.array([1,2,4,5])

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [95]:
c = a - b
c

array([20, 29, 38, 47])

In [96]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )
print(A*B)                         # element wise product

print([[1*2, 1*0],
       [0*3, 1*4]])

[[2 0]
 [0 4]]
[[2, 0], [0, 4]]


In [97]:
print(np.dot(A, B))
print([[1*2+ 1*3, 1*0+ 1*4],
       [0*2+1*3, 0*0+1*4]])

[[5 4]
 [3 4]]
[[5, 4], [3, 4]]


In [130]:
# np.arange - Creating sequence of Numbers

a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a / b
print(c)

[ 20.          15.          13.33333333  12.5       ]


In [129]:
c

array([ 20.        ,  15.        ,  13.33333333,  12.5       ])

In [131]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a // b
c


array([20, 15, 13, 12])

In [133]:
#Modulus operator can be applied on NumPy arrays as shown below. They apply element wise.
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a % b
c


array([0, 0, 1, 2])

In [134]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a ** b
c



array([     20,     900,   64000, 6250000])

In [135]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False], dtype=bool)

In [136]:
m < 25 

array([ True,  True, False, False], dtype=bool)

In [137]:
m[m < 25]

array([20, -5])

In [152]:
h = np.arange(5).reshape(1, 1, 5)
print(h)
print(h.shape)

[[[0 1 2 3 4]]]
(1, 1, 5)


In [146]:
b = np.array([10, 20, 30, 40, 50])
b.reshape(1,1,5)

array([[[10, 20, 30, 40, 50]]])

In [153]:
x = h + [10, 20, 30, 40, 50]
print(x)
print(x.shape)

[[[10 21 32 43 54]]]
(1, 1, 5)


In [144]:
h + [[[10, 20, 30, 40, 50]]]

array([[[10, 21, 32, 43, 54]]])

In [147]:
h + b.reshape(1,1,5)

array([[[10, 21, 32, 43, 54]]])

In [148]:
k = np.arange(6).reshape(2, 3)

In [149]:
k


array([[0, 1, 2],
       [3, 4, 5]])

In [151]:
k + [100, 200, 300] 

array([[100, 201, 302],
       [103, 204, 305]])

In [155]:
 k + [33, 44]

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [157]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print("mean =", a.mean())

mean = 6.76666666667


In [158]:
np.prod(a)

-71610.0

In [159]:
print(-2.5* 3.1* 7*10*11*12)

-71610.0


In [181]:
import math
a = np.array([1,3,4])
m = np.mean(a)
print(m)
print(a -m)
x = (a-m)**2
print(x)
s = np.sum(x)
print(s)
v = np.var(a)
print(v)
print(v*len(a))
print(np.std(a))
print(math.sqrt(s/len(a)))

2.66666666667
[-1.66666667  0.33333333  1.33333333]
[ 2.77777778  0.11111111  1.77777778]
4.66666666667
1.55555555556
4.66666666667
1.24721912892
1.247219128924647


In [182]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [183]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [3]:
import numpy as np
a = np.array([[10,20],[30,40]])
b = np.array([1])
print(a+b)

[[11 21]
 [31 41]]


In [4]:
import numpy as np
import pandas as pd

In [1]:
weights = {"alice": 68, "bob": 83, "colin": 86, "darwin": 68}

In [2]:
weights

{'alice': 68, 'bob': 83, 'colin': 86, 'darwin': 68}

In [5]:
s3 = pd.Series(weights)

In [7]:
s3 + s3

alice     136
bob       166
colin     172
darwin    136
dtype: int64

In [8]:
people["birthyear"]

NameError: name 'people' is not defined

In [9]:
people = pd.DataFrame(people_dict)

NameError: name 'people_dict' is not defined

In [10]:
d2 = pd.DataFrame(
        people_dict,
        columns=["birthyear", "weight", "height"],
        index=["bob", "alice", "eugene"]
     )

NameError: name 'people_dict' is not defined

In [81]:
a = np.array([[1, 2, 3],
[4, 5, 6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [80]:
a.sum(axis=0)

array([5, 7, 9])

In [79]:
a.sum(axis=1)

array([ 6, 15])

In [82]:
b = np.array([[.1, .2, .3],
[.4, .5, .6]])

In [84]:
from numpy import linalg

In [85]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)


In [87]:
solution

array([-3.,  2.])