In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
b = np.array((3, 4, 5))

In [5]:
type(b)

numpy.ndarray

In [13]:
x = np.zeros((3,4))  
type(x.dtype)

numpy.ndarray

In [10]:
x.shape

(3, 4)

In [16]:
y = np.ones( (3,4), dtype=np.int16 )  
y

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [18]:
print(x.dtype)
print(y.dtype)

float64
int16


In [25]:
np.full( (3,4), 0.11 )  

array([[ 0.11,  0.11,  0.11,  0.11],
       [ 0.11,  0.11,  0.11,  0.11],
       [ 0.11,  0.11,  0.11,  0.11]])

In [20]:
array([[ 3.14159265 ,  3.14159265 ,  3.14159265 ,  3.14159265 ],
       [ 3.14159265 ,  3.14159265 ,  3.14159265 ,  3.14159265 ],
       [ 3.14159265 ,  3.14159265 ,  3.14159265 ,  3.14159265 ]])

NameError: name 'array' is not defined

In [26]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [21]:
%timeit x

22.4 ns ± 0.0106 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


ERROR:root:File `'x.py'` not found.


In [29]:
np.arange( 0, 2, 0.3 ) 

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [38]:
x = [
        [
            [1],
            [1], 
            [1],
            [1]
        ],
        [
            [1],
            [1], 
            [1],
            [1]
        ]
]

In [39]:
np.array(x).shape

(2, 4, 1)

In [40]:
np.linspace(0, 5/3, 6)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
        1.66666667])

In [41]:
# Make a 2x3 matrix having random floats between 0 and 1:
np.random.rand(2,3)

array([[ 0.21288689,  0.20662218,  0.78018623],
       [ 0.35294004,  0.07347101,  0.54552084]])

In [52]:
x = np.empty((2,3))

In [53]:
x

array([[ 0.21288689,  0.20662218,  0.78018623],
       [ 0.35294004,  0.07347101,  0.54552084]])

In [54]:
x.ndim

2

In [55]:
x.shape

(2, 3)

In [59]:
x.size


6

In [58]:
x[0]

array([ 0.21288689,  0.20662218,  0.78018623])

In [60]:
c = np.arange(1, 5)

In [61]:
c

array([1, 2, 3, 4])

In [62]:
c.dtype

dtype('int64')

In [64]:
c.itemsize

8

In [66]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [69]:
b = a.reshape(2, 3)
print(b)

[[0 1 2]
 [3 4 5]]


In [73]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

19

In [75]:
a[2:5]

array([ 3, 19, 13])

In [81]:
print(a[2::2])
print(a[2::3])
print(a[::-1])

[ 3 13  3]
[3 7]
[ 3 13  3  1]


In [82]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[1:3] = -1
print(a)

[ 1 -1 -1 19 13  7  3]


In [71]:
b = [1, 2, 5, 7, 8]

In [72]:
b[1:3] = -1


TypeError: can only assign an iterable

In [84]:
a = np.array([1, 2, 5, 7, 8])
a_slice = a[1:5]
a_slice[1] = 1000
print(a)

[   1    2 1000    7    8]


In [87]:
another_slice = a[2:6].copy()
another_slice[1] = 23333
print(another_slice)
print(a)

[ 1000 23333     8]
[   1    2 1000    7    8]


In [90]:
x = np.random.rand(5,8)

In [91]:
x

array([[ 0.91295297,  0.01112513,  0.65864083,  0.66163387,  0.18084673,
         0.42521843,  0.89938507,  0.49546265],
       [ 0.56071606,  0.43758444,  0.64375008,  0.92215003,  0.5781699 ,
         0.48125833,  0.46411393,  0.43851094],
       [ 0.35931321,  0.79352878,  0.84762455,  0.12466979,  0.97632643,
         0.30259372,  0.83517866,  0.68199142],
       [ 0.54767285,  0.81770747,  0.59007675,  0.05625744,  0.50126431,
         0.36643128,  0.57118568,  0.72310451],
       [ 0.06969011,  0.84029301,  0.05352024,  0.05322677,  0.19078094,
         0.91325862,  0.98690071,  0.04413885]])

In [92]:
x[1]

array([ 0.56071606,  0.43758444,  0.64375008,  0.92215003,  0.5781699 ,
        0.48125833,  0.46411393,  0.43851094])

In [93]:
x[1, 1]

0.43758443823885318

In [95]:
x[0:2, 0:2]

array([[ 0.91295297,  0.01112513],
       [ 0.56071606,  0.43758444]])

In [100]:
x = np.random.rand(5,5, 5)

In [101]:
x

array([[[ 0.19907802,  0.18596918,  0.21651443,  0.03380817,  0.97940064],
        [ 0.48384454,  0.40302598,  0.27922243,  0.03069073,  0.16729342],
        [ 0.0094189 ,  0.85681666,  0.69393673,  0.55097882,  0.49890097],
        [ 0.20653228,  0.29270625,  0.2000002 ,  0.88554132,  0.85020175],
        [ 0.18272962,  0.99806737,  0.06880457,  0.18338868,  0.16965535]],

       [[ 0.49029765,  0.04489607,  0.32937092,  0.65560808,  0.27553171],
        [ 0.3975821 ,  0.31232761,  0.87412198,  0.15056015,  0.38648679],
        [ 0.6223746 ,  0.24616775,  0.37189256,  0.1349789 ,  0.71314284],
        [ 0.27301212,  0.97813757,  0.2631948 ,  0.41149151,  0.15225421],
        [ 0.05135565,  0.7792881 ,  0.79553848,  0.21911518,  0.61877098]],

       [[ 0.37849582,  0.43876909,  0.21580677,  0.2257849 ,  0.94514806],
        [ 0.42637846,  0.95463953,  0.02068619,  0.56799217,  0.81698795],
        [ 0.60509156,  0.40356471,  0.17217969,  0.58700892,  0.82484929],
        [ 0.68063815,

In [103]:
x[0:2, 0:2, 0:2]

array([[[ 0.19907802,  0.18596918],
        [ 0.48384454,  0.40302598]],

       [[ 0.49029765,  0.04489607],
        [ 0.3975821 ,  0.31232761]]])

In [104]:
a = np.arange(12).reshape(3, 4)

In [105]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
rows_on = np.array([ True, False, True])

In [107]:
rows_on

array([ True, False,  True], dtype=bool)

In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a[rows_on]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [111]:
a = np.array( [20, 30, 40, 50] )
b = np.arange( 4 )
c = a + b
c

array([20, 31, 42, 53])

In [112]:
c = a - b
c

array([20, 29, 38, 47])

In [116]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )
print(A*B)                         # element wise product

print([[1*2, 1*0],
       [0*3, 1*4]])

[[2 0]
 [0 4]]
[[2, 0], [0, 4]]


In [118]:
print(np.dot(A, B))
print([[1*2+ 1*3, 1*0+ 1*4],
       [0*2+1*3, 0*0+1*4]])

[[5 4]
 [3 4]]
[[5, 4], [3, 4]]


In [130]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a / b
print(c)

[ 20.          15.          13.33333333  12.5       ]


In [129]:
c

array([ 20.        ,  15.        ,  13.33333333,  12.5       ])

In [131]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a // b
c


array([20, 15, 13, 12])

In [133]:
#Modulus operator can be applied on NumPy arrays as shown below. They apply element wise.
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a % b
c


array([0, 0, 1, 2])

In [134]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a ** b
c



array([     20,     900,   64000, 6250000])

In [135]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False], dtype=bool)

In [136]:
m < 25 

array([ True,  True, False, False], dtype=bool)

In [137]:
m[m < 25]

array([20, -5])

In [152]:
h = np.arange(5).reshape(1, 1, 5)
print(h)
print(h.shape)

[[[0 1 2 3 4]]]
(1, 1, 5)


In [146]:
b = np.array([10, 20, 30, 40, 50])
b.reshape(1,1,5)

array([[[10, 20, 30, 40, 50]]])

In [153]:
x = h + [10, 20, 30, 40, 50]
print(x)
print(x.shape)

[[[10 21 32 43 54]]]
(1, 1, 5)


In [144]:
h + [[[10, 20, 30, 40, 50]]]

array([[[10, 21, 32, 43, 54]]])

In [147]:
h + b.reshape(1,1,5)

array([[[10, 21, 32, 43, 54]]])

In [148]:
k = np.arange(6).reshape(2, 3)

In [149]:
k


array([[0, 1, 2],
       [3, 4, 5]])

In [151]:
k + [100, 200, 300] 

array([[100, 201, 302],
       [103, 204, 305]])

In [155]:
 k + [33, 44]

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [157]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print("mean =", a.mean())

mean = 6.76666666667


In [158]:
np.prod(a)

-71610.0

In [159]:
print(-2.5* 3.1* 7*10*11*12)

-71610.0


In [181]:
import math
a = np.array([1,3,4])
m = np.mean(a)
print(m)
print(a -m)
x = (a-m)**2
print(x)
s = np.sum(x)
print(s)
v = np.var(a)
print(v)
print(v*len(a))
print(np.std(a))
print(math.sqrt(s/len(a)))

2.66666666667
[-1.66666667  0.33333333  1.33333333]
[ 2.77777778  0.11111111  1.77777778]
4.66666666667
1.55555555556
4.66666666667
1.24721912892
1.247219128924647


In [182]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [183]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])